version: '3'

networks:
    jenkins-net:
        driver: bridge
        ipam:
            config:
            -
                subnet: 192.168.1.0/24

services:
    nginx:
        image: nginx:alpine
        expose:
        - "80"
        ports:
        - "80:80"
        volumes:
        - "./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./nginx-conf/jenkins.conf:/etc/nginx/conf.d/default.conf:ro"
        networks:
            jenkins-net:
                ipv4_address: 192.168.1.2

    jenkins:
        build:
            context: .
            dockerfile: jenkins.Dockerfile
        volumes:
        - jenkins_home:/var/jenkins_home
        - "./email-config.xml:/var/jenkins_home/hudson.tasks.Mailer.xml"
        networks:
            jenkins-net:
                ipv4_address: 192.168.1.3

volumes:
    jenkins_home:
